### ISSUE TITLE
Recent Diffractometer changes have broken Mockup

### ISSUE THREAD

**Issue by rhfogh** [mxcube/mxcubecore#1504]
Trying to run a mockup with the most recent mxcubecore found it non-functional, with numerous errors. Fixes for some of the simpler ones are in a recent pull request, but not all. This (re)raises some questions:

- Did anyone test the mock version before pushing and merging those changes?
- Where can I go to find a mock configuration that works with the new code? Without that, how do I fix problems?  (yes, I know I have promised to do some clean-up here, but I have postponed that till 1) I have a known-to-be-working version to work from, and 2) we have finished the move to yaml configuration)
- What is the correct way of avoiding this kind of problem?

Finally, three concrete problems that need fixing, even after the parallel PR:

1) (This is on Qt, but comes back to a missing Diffractometer.omega)
```
Traceback (most recent call last):
  File "/home/rhfogh/pycharm/mxcubeqt/mxcubeqt/configuration.py", line 82, in load_brick
    new_instance = class_obj(None, brick_name)
  File "/home/rhfogh/pycharm/mxcubeqt/mxcubeqt/bricks/task_toolbox_brick.py", line 67, in __init__
    self.task_tool_box_widget = TaskToolBoxWidget(self)
  File "/home/rhfogh/pycharm/mxcubeqt/mxcubeqt/widgets/task_toolbox_widget.py", line 69, in __init__
    self.discrete_page = CreateDiscreteWidget(self.tool_box, "Discrete")
  File "/home/rhfogh/pycharm/mxcubeqt/mxcubeqt/widgets/create_discrete_widget.py", line 44, in __init__
    CreateTaskBase.__init__(
  File "/home/rhfogh/pycharm/mxcubeqt/mxcubeqt/widgets/create_task_base.py", line 96, in __init__
    HWR.beamline.diffractometer.omega.connect(
  File "/home/rhfogh/pycharm/mxcubecore/mxcubecore/CommandContainer.py", line 311, in __getattr__
    return super().__getattribute__(attr)
AttributeError: 'DiffractometerMockup' object has no attribute 'omega'
```

2) 

  File "/home/rhfogh/pycharm/mxcubeqt/mxcubeqt/bricks/tree_brick.py", line 445, in logged_in
    and HWR.beamline.diffractometer.use_sample_changer()

  File "/home/rhfogh/pycharm/mxcubecore/mxcubecore/CommandContainer.py", line 311, in __getattr__
    return super().__getattribute__(attr)

AttributeError: 'DiffractometerMockup' object has no attribute 'use_sample_changer'

3)                 
```
| zoom                         | MicrodiffZoomMockup          | udiff_zoom.yaml               | 1        |                                        
| diffractometer               | DiffractometerMockup         | minidiff.yaml                 | 28       | Error in DiffractometerMockup.init()   
| lims                         | ISPyBClientMockup            | lims.yaml                     | 76       |                                        
| camera                       | MDCameraMockup               | md_camera.yaml                | 10       |                                        
| sample_view                  | SampleView                   | sample_view.yaml              | 12       | Error in SampleView.init() 
```

Rasing the actual errors (in the mock web version this time) you get
```
Traceback (most recent call last):
  File "/home/rhfogh/pycharm/mxcubeweb/mxcubeweb/mxcubeweb/__init__.py", line 129, in build_server_and_config
    HWR.init_hardware_repository(
  File "/home/rhfogh/pycharm/mxcubeweb/mxcubecore/mxcubecore/HardwareRepository.py", line 410, in init_hardware_repository
    beamline = load_from_yaml(
  File "/home/rhfogh/pycharm/mxcubeweb/mxcubecore/mxcubecore/HardwareRepository.py", line 208, in load_from_yaml
    hwobj = load_from_yaml(
  File "/home/rhfogh/pycharm/mxcubeweb/mxcubecore/mxcubecore/HardwareRepository.py", line 246, in load_from_yaml
    result.init()
  File "/home/rhfogh/pycharm/mxcubeweb/mxcubecore/mxcubecore/HardwareObjects/mockup/DiffractometerMockup.py", line 62, in init
    super().init()
  File "/home/rhfogh/pycharm/mxcubeweb/mxcubecore/mxcubecore/HardwareObjects/abstract/AbstractDiffractometer.py", line 223, in init
    for role in self.config.motors:
AttributeError: 'HOConfig' object has no attribute 'motors'
Traceback (most recent call last):
  File "/home/rhfogh/Software/miniconda3/envs/mxcubeweb/bin/mxcubeweb-server", line 6, in <module>
    sys.exit(main())
  File "/home/rhfogh/pycharm/mxcubeweb/mxcubeweb/mxcubeweb/__init__.py", line 172, in main
    server, cfg = build_server_and_config()
  File "/home/rhfogh/pycharm/mxcubeweb/mxcubeweb/mxcubeweb/__init__.py", line 129, in build_server_and_config
    HWR.init_hardware_repository(
  File "/home/rhfogh/pycharm/mxcubeweb/mxcubecore/mxcubecore/HardwareRepository.py", line 410, in init_hardware_repository
    beamline = load_from_yaml(
  File "/home/rhfogh/pycharm/mxcubeweb/mxcubecore/mxcubecore/HardwareRepository.py", line 208, in load_from_yaml
    hwobj = load_from_yaml(
  File "/home/rhfogh/pycharm/mxcubeweb/mxcubecore/mxcubecore/HardwareRepository.py", line 246, in load_from_yaml
    result.init()
  File "/home/rhfogh/pycharm/mxcubeweb/mxcubecore/mxcubecore/HardwareObjects/mockup/DiffractometerMockup.py", line 62, in init
    super().init()
  File "/home/rhfogh/pycharm/mxcubeweb/mxcubecore/mxcubecore/HardwareObjects/abstract/AbstractDiffractometer.py", line 223, in init
    for role in self.config.motors:
AttributeError: 'HOConfig' object has no attribute 'motors'

```
It looks like these are a matter of setting the right configuration, but, again, what is the place to go for finding an up-to-date configuration for a mock run?

**Comment by mockoocy** [comment]
I think there is no working configuration for web at this moment, at least using current version of mxcubecore.
mxcubeweb has had a change in the  `pyproject.toml` specification, forcing it to use version of mxcubecore before the `AbstractDiffractometer` changes.

I believe that in order to use web version of mxcube with latest core, https://github.com/mxcube/mxcubeweb/pull/2000 needs to be merged first.
For the Qt frontend, similar changes will probably need to be made.

**Comment by beteva** [comment]
Dear @rhfogh, my apologies, I did not pay attention that you were having issues with the Qt version. I believe some changes of the configuration file are indeed needed.
@mockoocy , now that the merge has been done, the web configuration for both xml and yaml files is working.

**Comment by rhfogh** [comment]
Now that the mxcubeweb demo.yaml directory has been updated and committed these problems have been fixed (except the mxcubeqt ones, but that is a different story).

For the future I would recommend not to merge a change that depends on changed configuration files unless the configuration file changes are merged at the same time. Otehrwise, how can othes make them work?
